services:
  - type: web
    name: mezon-uni-pal
    env: node
    buildCommand: |
      npm install
    startCommand: |
      apt-get update && \
      apt-get install -y chromium && \
      node index.js
    envVars:
      - key: NODE_ENV
        value: production
